apiVersion: v1
kind: Service
metadata:
  name: service-backend-devops
  namespace: haproxy-controller-devops
  labels:
    run: ingress-default-backend

spec:
  selector:
      run: ingress-default-backend

  ports:
    - name: port-backend
      port: 8080
      protocol: TCP
      targetPort: 8080
